set_property IOSTANDARD LVCMOS33 [get_ports {n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports rst]
set_property PACKAGE_PIN K17 [get_ports {result[11]}]
set_property PACKAGE_PIN W9 [get_ports {n[3]}]
set_property PACKAGE_PIN Y7 [get_ports {n[2]}]
set_property PACKAGE_PIN Y8 [get_ports {n[1]}]
set_property PACKAGE_PIN AB8 [get_ports {n[0]}]
set_property PACKAGE_PIN L13 [get_ports {result[10]}]
set_property PACKAGE_PIN M13 [get_ports {result[9]}]
set_property PACKAGE_PIN K14 [get_ports {result[8]}]
set_property PACKAGE_PIN K13 [get_ports {result[7]}]
set_property PACKAGE_PIN M20 [get_ports {result[6]}]
set_property PACKAGE_PIN N20 [get_ports {result[5]}]
set_property PACKAGE_PIN N19 [get_ports {result[4]}]
set_property PACKAGE_PIN M17 [get_ports {result[3]}]
set_property PACKAGE_PIN M16 [get_ports {result[2]}]
set_property PACKAGE_PIN M15 [get_ports {result[1]}]
set_property PACKAGE_PIN K16 [get_ports {result[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[0]_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[0]_i_4]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[1]_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[1]_i_4]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[2]_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[2]_i_4]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[3]_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[3]_i_4]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[4]_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[4]_i_4]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[5]_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[5]_i_4]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[6]_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[6]_i_4]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells myid/displaydata[7]_i_2]]
set_property SEVERITY {Warning} [get_drc_checks LUTLP-1]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]